export const COUPLE_STATUS = {
  COUPLED: 'COUPLED',
  NOT_COUPLED: 'NOT_COUPLED',
  DISCONNECTED_BY_ME: 'DISCONNECTED_BY_ME',
  DISCONNECTED_BY_PARTNER: 'DISCONNECTED_BY_PARTNER',
  DISCONNECTED_EXPIRED: 'DISCONNECTED_EXPIRED',
} as const;

export type CoupleStatus = (typeof COUPLE_STATUS)[keyof typeof COUPLE_STATUS];
