/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 이전 커플 데이터 이관 응답
 */
export interface AdminCoupleMigrationResponse {
  /** 이전 커플 수 */
  previousCoupleCount?: number;
  /** 생성된 일반 앨범 수 */
  createdAlbumCount?: number;
  /** 이동된 사진 수 */
  movedPhotoCount?: number;
  /** 이동된 댓글 수 */
  movedCommentCount?: number;
  /** 건너뛴 댓글 수 */
  skippedCommentCount?: number;
  /** 이동된 이모티콘 수 */
  movedEmoticonCount?: number;
  /** 건너뛴 이모티콘 수 */
  skippedEmoticonCount?: number;
}
