/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 관리자 작업 공통 응답
 */
export interface AdminActionResponse {
  /** 작업 결과 메시지 */
  message?: string;
}
