/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 관리자 사용자 조회 응답
 */
export interface AdminUserSummaryResponse {
  /** 사용자 ID */
  id?: number;
  /** 사용자 이메일 */
  email?: string;
}
