/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { AuthTokens } from './authTokens';

/**
 * 관리자 커플 파트너 생성 응답
 */
export interface AdminPartnerResponse {
  /** 파트너 이메일 */
  partnerEmail?: string;
  tokens?: AuthTokens;
}
