/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { BoundingBoxResponse } from './boundingBoxResponse';

/**
 * 앨범 지도 정보 응답
 */
export interface AlbumMapInfoResponse {
  /** 앨범 ID */
  albumId?: number;
  /** 센터 경도 (사진이 없으면 null) */
  centerLongitude?: number;
  /** 센터 위도 (사진이 없으면 null) */
  centerLatitude?: number;
  /** 바운딩 박스 (사진이 없으면 null) */
  boundingBox?: BoundingBoxResponse;
}
