/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { PhotoResponse } from './photoResponse';

/**
 * 앨범별 사진 목록
 */
export interface AlbumWithPhotosResponse {
  /** 앨범 ID */
  id?: number;
  /** 앨범 제목 */
  title?: string;
  /** 사진 개수 */
  photoCount?: number;
  /** 썸네일 URL */
  thumbnailUrl?: string;
  /** 앨범 내 사진 목록 */
  photos?: PhotoResponse[];
  isEditable?: boolean;
}
