/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 앨범 생성 요청
 */
export interface AlbumRequest {
  /**
   * 앨범 제목
   * @minLength 0
   * @maxLength 10
   */
  title?: string;
  /** 워크스페이스 ID */
  workspaceId?: number;
}
