/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 앨범 썸네일 정보
 */
export interface AlbumThumbnails {
  /** 앨범 ID */
  id?: number;
  /** 앨범 ID */
  title?: string;
  /** 앨범 ID */
  photoCount?: number;
  /** 앨범 썸네일 사진들 (최대 4장) */
  thumbnailUrls?: string[];
}
