/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorDetail } from './errorDetail';

/**
 * API 응답
 */
export interface ApiResponseErrorDetail {
  /** HTTP 상태 코드 */
  code?: number;
  /** 응답 메시지 */
  message?: string;
  /** 응답 데이터 */
  data?: ErrorDetail;
}
