/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 바운딩 박스 응답
 */
export interface BoundingBoxResponse {
  /** 서쪽 경도 (최소 경도) */
  west?: number;
  /** 남쪽 위도 (최소 위도) */
  south?: number;
  /** 동쪽 경도 (최대 경도) */
  east?: number;
  /** 북쪽 위도 (최대 위도) */
  north?: number;
}
