/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 클러스터 내 사진 상세 응답
 */
export interface ClusterPhotoResponse {
  /** 사진 ID */
  id?: number;
  /** 사진 URL */
  url?: string;
  /** 경도 */
  longitude?: number;
  /** 위도 */
  latitude?: number;
  /** 생성일시 */
  createdAt?: string;
}
