/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 클러스터 내 사진 상세 응답
 */
export interface ClusterPhotoResponse {
  /** 사진 ID */
  id?: number;
  /** 사진 URL */
  url?: string;
  /**
   * 사진 경도
   * @minimum 124
   * @maximum 132
   */
  longitude: number;
  /**
   * 사진 위도
   * @minimum 33
   * @maximum 39
   */
  latitude: number;
  /** 촬영일시 (ISO 8601 형식) */
  takenAt?: string;
  /** 주소 */
  address?: string;
}
