/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 클러스터 응답
 */
export interface ClusterResponse {
  /** 클러스터 ID (줌 레벨 + 그리드 셀 인덱스) */
  clusterId?: string;
  /** 클러스터 내 사진 개수 */
  count?: number;
  /** 대표 썸네일 URL (가장 최근 생성된 사진) */
  thumbnailUrl?: string;
  /**
   * 클러스터 중심 경도
   * @minimum 124
   * @maximum 132
   */
  longitude: number;
  /**
   * 클러스터 중심 위도
   * @minimum 33
   * @maximum 39
   */
  latitude: number;
}
