/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { ClusterPhotoResponse } from './clusterPhotoResponse';

/**
 * 클러스터 사진 목록 페이지네이션 응답
 */
export interface ClusterPhotosPageResponse {
  /** 사진 목록 */
  photos?: ClusterPhotoResponse[];
  /** 현재 페이지 번호 (0부터 시작) */
  page?: number;
  /** 페이지 크기 */
  size?: number;
  /** 전체 사진 개수 */
  totalElements?: number;
  /** 전체 페이지 수 */
  totalPages?: number;
  /** 마지막 페이지 여부 */
  last?: boolean;
}
