/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { PartnerSummaryResponse } from './partnerSummaryResponse';

/**
 * 커플 상태 조회 응답
 */
export interface CoupleStatusResponse {
  partnerSummary?: PartnerSummaryResponse;
  /** 커플 연결 여부 */
  isCoupled?: boolean;
}
