/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { PartnerSummaryResponse } from './partnerSummaryResponse';

/**
 * 커플 연결 확정 응답
 */
export interface CoupleLinkResponse {
  coupleId?: number;
  partnerSummary?: PartnerSummaryResponse;
}
