/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 워크스페이스 생성 요청
 */
export interface CreateWorkspaceRequest {
  /**
   * 워크스페이스 이름
   * @minLength 0
   * @maxLength 20
   */
  name: string;
}
