/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 커플 생성 요청
 */
export interface CreateCoupleRequest {
  /**
   * 커플 이름
   * @minLength 0
   * @maxLength 20
   */
  name: string;
}
