/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 사진 생성 요청
 */
export interface CreatePhotoRequest {
  /**
   * 사진 URL
   * @minLength 1
   */
  url: string;
  /** 앨범 ID */
  albumId?: number;
  /** 경도 */
  longitude: number;
  /** 위도 */
  latitude: number;
  /** 촬영일시 (EXIF 데이터) */
  takenAt: string;
  /** 사진 설명 */
  description?: string;
}
