/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 이모지 요약 정보
 */
export interface EmoticonSummaryResponse {
  /** 이모지 */
  emoji?: string;
  /** 이모지 개수 */
  count?: number;
  /** 현재 사용자가 반응했는지 여부 */
  reacted?: boolean;
}
