/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 필드별 에러 목록
 */
export type ErrorDetailErrors = {[key: string]: string};
