/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorDetailErrors } from './errorDetailErrors';

/**
 * 에러 상세 정보
 */
export interface ErrorDetail {
  /** 에러 코드 */
  errorCode?: string;
  /** 에러 상세 메시지 */
  detail?: string;
  /** 요청 URI */
  instance?: string;
  /** 필드별 에러 목록 */
  errors?: ErrorDetailErrors;
}
