/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

export type GetClusterPhotosParams = {
/**
 * 페이지 번호 (0부터 시작)
 */
page?: number;
/**
 * 페이지 크기
 */
size?: number;
};
