/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

export type GetLocationInfoParams = {
/**
 * 경도
 */
lng: number;
/**
 * 위도
 */
lat: number;
};
