/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

export type GetMapMeParams = {
  /**
   * 경도
   */
  longitude: number;
  /**
   * 위도
   */
  latitude: number;
  /**
   * 줌 레벨(소수점 지원). 15 미만이면 클러스터링, 15 이상이면 개별 사진 반환
   */
  zoom: number;
  /**
   * 앨범 ID (선택). 지정 시 해당 앨범의 사진만 조회
   */
  albumId?: number;
  /**
   * 이전 응답의 dataVersion. 클라이언트 캐시 동기화 판단에 사용
   */
  lastDataVersion?: number;
};
