/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

export type GetPhotos1Params = {
  /**
   * 줌 레벨 (0-20). 15 미만이면 클러스터링, 15 이상이면 개별 사진 반환
   */
  zoom: number;
  /**
   * 바운딩 박스 (west,south,east,north 형식의 경도/위도)
   */
  bbox: string;
  /**
   * 앨범 ID (선택). 지정 시 해당 앨범의 사진만 조회
   */
  albumId?: number;
};
