/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { LocationInfoResponse } from './locationInfoResponse';
import type { BoundingBoxResponse } from './boundingBoxResponse';
import type { AlbumThumbnails } from './albumThumbnails';

/**
 * 홈 응답
 */
export interface HomeResponse {
  /** 위치 정보 */
  location?: LocationInfoResponse;
  /** 바운딩 박스 (사진이 없으면 null) */
  boundingBox?: BoundingBoxResponse;
  /** 앨범 하이라이트 사진들 (최대 4장) */
  albums?: AlbumThumbnails[];
}
