/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * ID 응답
 */
export interface IdResponse {
  /** 생성된 리소스의 ID */
  id?: number;
}
