/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 초대 코드 응답
 */
export interface InviteCodeResponse {
  inviteCode?: string;
  expiresAt?: string;
}
