/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 초대코드 검증 응답
 */
export interface InviteCodePreviewResponse {
  inviterUserId?: number;
  nickname?: string;
  profileImageUrl?: string;
}
