/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 커플 합류 요청
 */
export interface JoinCoupleRequest {
  /**
   * 초대 코드
   * @minLength 8
   * @maxLength 8
   */
  inviteCode: string;
}
