/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

export type KakaoAuthorizeParams = {
/**
 * 로그인 후 리다이렉트할 프론트엔드 URL
 */
redirect?: string;
};
