/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 카카오 로그인 요청 (Authorization Code)
 */
export interface KakaoLoginRequest {
  /** 카카오 인가 코드 */
  code?: string;
}
