/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 위치 정보
 */
export interface LocationResponse {
  /** 경도 */
  longitude?: number;
  /** 위도 */
  latitude?: number;
}
