/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 위치 정보 응답
 */
export interface LocationInfoResponse {
  /** 주소 */
  address?: string;
  /** 장소명 */
  placeName?: string;
  /** 지역명 */
  regionName?: string;
}
