/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 로그인 요청
 */
export interface LoginRequest {
  /** 사용자 이메일 */
  email: string;
}
