/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { LocationInfoResponse } from './locationInfoResponse';
import type { BoundingBoxResponse } from './boundingBoxResponse';
import type { AlbumThumbnails } from './albumThumbnails';
import type { ClusterResponse } from './clusterResponse';
import type { MapPhotoResponse } from './mapPhotoResponse';

/**
 * 지도 ME 응답 (홈 + 사진 조회 통합)
 */
export interface MapMeResponse {
  /** 위치 정보 */
  location?: LocationInfoResponse;
  /** 바운딩 박스 */
  boundingBox?: BoundingBoxResponse;
  /** 기록 수(전체 보기 사진 개수) */
  totalHistoryCount?: number;
  /** 앨범 하이라이트 사진들 (최대 4장) */
  albums?: AlbumThumbnails[];
  /** 데이터 버전 (사진 변경 시 증가, 프론트 캐싱에 사용) */
  dataVersion?: number;
  /** 클러스터 목록 (줌 < 15일 때) */
  clusters?: ClusterResponse[];
  /** 개별 사진 목록 (줌 >= 15일 때) */
  photos?: MapPhotoResponse[];
}
