/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { ClusterResponse } from './clusterResponse';
import type { MapPhotoResponse } from './mapPhotoResponse';

/**
 * 지도 사진 조회 응답
 */
export interface MapPhotosResponse {
  /** 클러스터 목록 (줌 < 15일 때) */
  clusters?: ClusterResponse[];
  /** 개별 사진 목록 (줌 >= 15일 때) */
  photos?: MapPhotoResponse[];
}
