/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 개별 사진 응답 (줌 >= 15)
 */
export interface MapPhotoResponse {
  /** 사진 ID */
  id?: number;
  /** 썸네일 URL */
  thumbnailUrl?: string;
  /** 경도 */
  longitude?: number;
  /** 위도 */
  latitude?: number;
  /** 촬영일 (yyyy.MM.dd 형식) */
  date?: string;
}
