/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 마이페이지 조회 응답
 */
export interface MyPageResponse {
  /** 내 닉네임 */
  myName?: string;
  /** 내 프로필 이미지 URL */
  myProfileImageUrl?: string;
  /** 상대방 닉네임 */
  partnerName?: string;
  /** 상대방 프로필 이미지 URL */
  partnerProfileImageUrl?: string;
  /** 로킷을 커플 연결한 이후 지금까지의 사용한 날짜 (미연결 시 null) */
  coupledDay?: number;
  /** 커플 내 전체 사진 수 */
  couplePhotoCount?: number;
}
