/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 마이페이지 조회 응답
 */
export interface MyPageResponse {
  /** 내 이메일 */
  myEmail?: string;
  /** 내 닉네임 */
  myName?: string;
  /** 내 프로필 이미지 URL */
  myProfileImageUrl?: string;
  /** 상대방 닉네임 */
  partnerName?: string;
  /** 상대방 프로필 이미지 URL */
  partnerProfileImageUrl?: string;
  /** 처음 만난 날짜 (미설정 시 null) */
  firstMetDate?: string;
  /** 처음 만난 날짜 기준 D-Day (미설정 시 null) */
  coupledDay?: number;
  /** 커플 내 전체 사진 수 */
  couplePhotoCount?: number;
}
