/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 파트너 요약 정보
 */
export interface PartnerSummaryResponse {
  userId?: number;
  nickname?: string;
  profileImageUrl?: string;
}
