/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 사진 상세 정보
 */
export interface PhotoDetailResponse {
  /** 사진 ID */
  id?: number;
  /** 사진 URL */
  url?: string;
  /** 촬영일 (yyyy.MM.dd 형식) */
  takenAt?: string;
  /** 앨범명 */
  albumName?: string;
  /** 등록자 이름 */
  uploaderName?: string;
  /** 도로명 주소 */
  address?: string;
  /** 사진 설명 */
  description?: string;
}
