/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { LocationResponse } from './locationResponse';

/**
 * 사진 정보
 */
export interface PhotoResponse {
  /** 사진 ID */
  id?: number;
  /** 사진 URL */
  url?: string;
  /** 위치 정보 */
  location?: LocationResponse;
  /** 사진 설명 */
  description?: string;
  /** 사진의 촬영 일시 */
  takenAt?: string;
  isEditable?: boolean;
}
