/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { AlbumWithPhotosResponse } from './albumWithPhotosResponse';

/**
 * 사진 목록 응답 (앨범별 그룹)
 */
export interface PhotoListResponse {
  /** 앨범별 사진 목록 */
  albums?: AlbumWithPhotosResponse[];
}
