/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 장소 정보
 */
export interface PlaceResponse {
  /** 장소명 */
  placeName?: string;
  /** 지번 주소 */
  address?: string;
  /** 도로명 주소 */
  roadAddress?: string;
  /** 경도 */
  longitude?: number;
  /** 위도 */
  latitude?: number;
  /** 카테고리 */
  category?: string;
}
