/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { PlaceResponse } from './placeResponse';

/**
 * 장소 검색 응답
 */
export interface PlaceSearchResponse {
  /** 검색된 장소 목록 */
  places?: PlaceResponse[];
}
