/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 장소 정보
 */
export interface PlaceResponse {
  /** 장소명 */
  placeName?: string;
  /** 주소 */
  address?: string;
  /** 도로명 주소 */
  roadAddress?: string;
  /**
   * 클러스터 중심 경도
   * @minimum 124
   * @maximum 132
   */
  longitude: number;
  /**
   * 클러스터 중심 위도
   * @minimum 33
   * @maximum 39
   */
  latitude: number;
  /** 카테고리 */
  category?: string;
}
