/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * Presigned URL 응답
 */
export interface PresignedUrl {
  /** S3 업로드용 Presigned URL */
  presignedUrl?: string;
  /** 업로드 완료 후 접근 가능한 객체 URL */
  objectUrl?: string;
}
