/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * Presigned URL 요청
 */
export interface PresignedUrlRequest {
  /**
   * 파일명
   * @minLength 1
   */
  fileName: string;
  /**
   * 파일 MIME 타입
   * @minLength 1
   */
  contentType: string;
}
