/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 리프레시 토큰 요청
 */
export interface RefreshTokenRequest {
  /** 리프레시 토큰 */
  refreshToken?: string;
}
