/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 이모지 제거 요청
 */
export interface RemoveEmoticonRequest {
  /**
   * 이모지
   * @minLength 1
   */
  emoji: string;
}
