/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 알림 이메일 저장 요청
 */
export interface SaveNotificationEmailRequest {
  /**
   * 알림 수신 이메일
   * @minLength 1
   */
  email: string;
}
