/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { SelectableAlbum } from './selectableAlbum';

/**
 * 선택 가능한 앨범 응답
 */
export interface SelectableAlbumResponse {
  /** 선택 가능한 앨범 목록 */
  albums?: SelectableAlbum[];
}
