/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 선택 가능한 앨범 정보
 */
export interface SelectableAlbum {
  /** 앨범 ID */
  id?: number;
  /** 앨범 제목 */
  title?: string;
  /** 앨범 내 사진 수 */
  photoCount?: number;
  /** 앨범 썸네일 URL */
  thumbnailUrl?: string;
  editable?: boolean;
  /** 조회자가 해당 앨범을 수정/삭제할 수 있는지 여부 */
  isEditable?: boolean;
}
