/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 처음 만난 날짜 수정 요청
 */
export interface UpdateFirstMetDateRequest {
  /** 처음 만난 날짜 */
  firstMetDate: string;
}
