/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 사진 수정 요청
 */
export interface UpdatePhotoRequest {
  /** 앨범 ID */
  albumId: number;
  /** 경도 */
  longitude: number;
  /** 위도 */
  latitude: number;
  /** 사진 설명 */
  description?: string;
}
