/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 프로필 사진 수정 요청
 */
export interface UpdateProfileImageRequest {
  /**
   * 프로필 사진 URL
   * @minLength 1
   */
  profileImageUrl: string;
}
