/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 닉네임 수정 요청
 */
export interface UpdateNicknameRequest {
  /**
   * 닉네임
   * @minLength 0
   * @maxLength 10
   */
  nickname: string;
}
