/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 초대코드 검증 요청
 */
export interface VerifyInviteCodeRequest {
  /**
   * @minLength 6
   * @maxLength 6
   * @pattern ^\d{6}$
   */
  inviteCode: string;
}
